package analyzer

type RulePreset struct {
	Key         string   `json:"key"`
	Label       string   `json:"label"`
	Description string   `json:"description"`
	RuleKeys    []string `json:"ruleKeys"`
}

func AllPresets() []RulePreset {
	allKeys := make([]string, 0)
	for _, rule := range AllRuleDefinitions() {
		allKeys = append(allKeys, rule.Key)
	}

	return []RulePreset{
		{
			Key:         "full_scan",
			Label:       "Full Scan",
			Description: "All 130+ checks for maximum coverage",
			RuleKeys:    allKeys,
		},
		{
			Key:         "essential",
			Label:       "Essential",
			Description: "Core SEO checks every site needs",
			RuleKeys: []string{
				"title_exists", "title_length", "meta_description_exists", "meta_description_length",
				"h1_count", "h1_not_empty", "images_alt_text",
				"canonical_exists", "meta_robots_noindex", "http_status_ok",
				"robots_txt_exists", "sitemap_exists",
				"uses_https", "mobile_viewport",
				"internal_links_present", "broken_internal_links",
				"page_size", "ttfb",
			"broken_scripts", "broken_stylesheets", "broken_images",
			},
		},
		{
			Key:         "blog",
			Label:       "Blog / Article",
			Description: "Optimized for content-heavy sites and blogs",
			RuleKeys: []string{
				"title_exists", "title_length", "title_multiple",
				"meta_description_exists", "meta_description_length",
				"h1_count", "h1_not_empty", "heading_hierarchy", "heading_not_empty",
				"images_alt_text", "images_alt_descriptive", "images_lazy_loading", "images_modern_format",
				"content_word_count", "content_text_html_ratio",
				"canonical_exists", "canonical_self_ref",
				"meta_robots_noindex", "http_status_ok",
				"jsonld_exists", "jsonld_valid", "jsonld_breadcrumb",
				"og_title", "og_description", "og_image", "og_type",
				"twitter_card", "twitter_title", "twitter_image",
				"hreflang_valid",
				"eeat_author", "eeat_copyright",
				"eeat_about_page", "eeat_contact_page", "eeat_privacy_policy",
				"duplicate_content_body", "duplicate_titles", "duplicate_descriptions",
				"internal_links_present", "internal_links_anchor_text",
				"page_size", "ttfb",
				"uses_https",
				"mobile_viewport",
				"sitemap_exists", "sitemap_coverage",
				"geo_llms_txt_exists", "geo_citability_question_headings",
				"geo_citability_faq", "geo_citability_lists",
				"geo_ai_descriptive_headings", "geo_ai_freshness", "geo_ai_semantic_html",
			},
		},
		{
			Key:         "ecommerce",
			Label:       "E-Commerce",
			Description: "Product pages, catalog, and transactional sites",
			RuleKeys: []string{
				"title_exists", "title_length", "title_multiple",
				"meta_description_exists", "meta_description_length",
				"h1_count", "h1_not_empty",
				"images_alt_text", "images_alt_descriptive", "images_dimensions",
				"images_modern_format", "images_lazy_loading",
				"canonical_exists", "canonical_absolute", "canonical_self_ref",
				"meta_robots_noindex", "http_status_ok", "crawl_depth",
				"pagination_rel_tags",
				"robots_txt_exists", "robots_txt_sitemap",
				"sitemap_exists", "sitemap_valid_xml", "sitemap_size",
				"sitemap_coverage", "sitemap_broken_urls",
				"jsonld_exists", "jsonld_valid", "jsonld_breadcrumb",
				"uses_https", "mixed_content", "hsts_header",
				"security_csp",
				"og_title", "og_description", "og_image",
				"twitter_card",
				"mobile_viewport", "mobile_viewport_config",
				"internal_links_present", "broken_internal_links",
				"external_links_rel",
				"page_size", "ttfb", "compression",
				"js_file_count", "css_file_count", "render_blocking",
			"total_requests", "cache_headers",
			"broken_scripts", "broken_stylesheets", "broken_images",
			"url_lowercase", "url_length", "url_special_chars",
			"duplicate_content_body", "duplicate_titles", "duplicate_descriptions",
			"geo_entity_org_schema",
			},
		},
		{
			Key:         "video",
			Label:       "Video Platform",
			Description: "Video-centric sites (YouTube-like, courses, streaming)",
			RuleKeys: []string{
				"title_exists", "title_length",
				"meta_description_exists", "meta_description_length",
				"h1_count",
				"images_alt_text",
				"canonical_exists", "meta_robots_noindex", "http_status_ok",
				"jsonld_exists", "jsonld_valid",
				"og_title", "og_description", "og_image", "og_type", "og_url",
				"twitter_card", "twitter_title", "twitter_description", "twitter_image",
				"sitemap_exists", "sitemap_video",
				"mobile_viewport", "mobile_viewport_config",
				"uses_https",
				"page_size", "ttfb", "compression",
				"render_blocking", "js_file_count",
				"hreflang_valid",
				"geo_llms_txt_exists",
				"geo_ai_semantic_html", "geo_ai_descriptive_headings",
				"geo_entity_org_schema", "geo_entity_social",
			},
		},
		{
			Key:         "landing_page",
			Label:       "Landing Page",
			Description: "Single-page sites and marketing landing pages",
			RuleKeys: []string{
				"title_exists", "title_length",
				"meta_description_exists", "meta_description_length",
				"h1_count", "h1_not_empty",
				"images_alt_text", "images_dimensions", "images_modern_format", "images_lazy_loading",
				"canonical_exists",
				"meta_robots_noindex", "http_status_ok",
				"og_title", "og_description", "og_image", "og_url", "og_type",
				"twitter_card", "twitter_title", "twitter_image",
				"uses_https", "hsts_header",
				"mobile_viewport", "mobile_viewport_config",
				"html_lang", "viewport_meta", "charset_meta",
				"page_size", "html_size", "ttfb", "compression",
				"js_file_count", "css_file_count", "render_blocking",
				"cache_headers",
				"jsonld_exists", "jsonld_valid",
				"geo_entity_org_schema",
			},
		},
		{
			Key:         "technical_only",
			Label:       "Technical SEO",
			Description: "Infrastructure, crawlability, and indexation only",
			RuleKeys: []string{
				"canonical_exists", "canonical_absolute", "canonical_self_ref", "canonical_conflict",
				"meta_robots_noindex", "meta_robots_conflict",
				"http_status_ok", "crawl_depth",
				"pagination_rel_tags",
				"robots_txt_exists", "robots_txt_size", "robots_txt_sitemap", "robots_txt_syntax",
				"sitemap_exists", "sitemap_valid_xml", "sitemap_index",
				"sitemap_size", "sitemap_freshness", "sitemap_coverage",
				"sitemap_orphan_urls", "sitemap_broken_urls", "sitemap_redirect_urls",
				"sitemap_robots_conflict", "sitemap_image", "sitemap_video",
				"redirect_chains", "temporary_redirects",
				"uses_https", "mixed_content", "hsts_header",
			"broken_internal_links", "broken_external_links",
			"broken_scripts", "broken_stylesheets", "broken_images",
			"url_lowercase", "url_hyphens", "url_length",
			"url_special_chars", "url_double_slash", "url_parameters",
			"duplicate_content_body", "duplicate_titles", "duplicate_descriptions",
			},
		},
		{
			Key:         "geo_only",
			Label:       "GEO / AI Readiness",
			Description: "AI search engine optimization checks only",
			RuleKeys: []string{
				"geo_crawler_oai-searchbot", "geo_crawler_perplexitybot",
				"geo_crawler_claude-searchbot", "geo_crawler_google-extended",
				"geo_crawler_applebot",
				"geo_crawler_block_gptbot", "geo_crawler_block_ccbot",
				"geo_llms_txt_exists", "geo_llms_full_txt",
				"geo_llms_txt_h1", "geo_llms_txt_blockquote",
				"geo_llms_txt_sections", "geo_llms_txt_links",
				"geo_entity_org_schema", "geo_entity_social",
				"geo_citability_statistics", "geo_citability_faq",
				"geo_citability_tables", "geo_citability_lists",
				"geo_citability_question_headings",
				"geo_ai_descriptive_headings", "geo_ai_freshness", "geo_ai_semantic_html",
				"jsonld_exists", "jsonld_valid",
				"robots_txt_exists",
			},
		},
	}
}
